# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'MovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB
  #pod 'Alamofire', '~> 5.2'
  pod 'ObjectMapper', '~> 3.3'
  pod "KRProgressHUD"
  pod 'SDWebImage', '~> 5.0'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.2'
  
end
